### ISSUE TITLE
"MyTheme extends ValoTheme" isn't possible with Vaadin 8

### ISSUE THREAD

**Issue by nikkijuk** [vaadin-marcus/vaadin-tips#1]
Vaadin 8 ValoTheme contains private constructor, which makes it impossible to extend ValoTheme.  It would be nice to see this demo as Vaadin 8 version, and even before it it would be good if "best practices" like using valo theme names thru own class would be compatible with future versions of Vaadin or it would be clarified if this isn't anymore right way to go.

**Comment by marcushellberg** [comment]
Hey! Thanks for letting me know. Apparently this broke accidentally while we were cleaning up code after static code analysis. We'll revert this and it should continue working as before.

**Comment by nikkijuk** [comment]
Thanks. I'll report some other things later when I have played more with Vaadin 8, but basically this was something one could see right both ways: inheritance is here hiding where style names are actually defined, i.e. if style is standard valo style or self defined, and this might be negative - but on the other hand, as style names are final constants, it's handy that one can't define same name twice, and in the end they come anyway thru inheritance when sass files are compiled.

**Comment by marcushellberg** [comment]
If you find any bugs in the framework itself, it's better to add them to https://github.com/vaadin/vaadin as I don't always remember to check my github comments that often :)
